package com.kyle.lightjourney;

import android.app.*;import android.content.*;import android.graphics.Color;import android.media.MediaPlayer;import android.media.audiofx.Visualizer;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 static final int PICK=42; Handler h=new Handler(Looper.getMainLooper()); MediaPlayer mp; Visualizer av; VizView viz; LinearLayout panel; TextView song,time; SeekBar seek; Button play;
 Runnable clock=()->{if(mp!=null){seek.setMax(Math.max(1,mp.getDuration()));seek.setProgress(mp.getCurrentPosition());time.setText(fmt(mp.getCurrentPosition())+" / "+fmt(mp.getDuration()));}h.postDelayed(clock,250);};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);build();h.post(clock);}
 void build(){FrameLayout root=new FrameLayout(this);viz=new VizView(this);root.addView(viz,new FrameLayout.LayoutParams(-1,-1));
  panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(d(16),d(12),d(16),d(14));panel.setBackgroundColor(0xD9000008);
  song=t("MUSIC LIGHT",18,Color.WHITE);time=t("0:00 / 0:00",12,0xffbbbbc8);panel.addView(song);panel.addView(time);
  seek=new SeekBar(this);panel.addView(seek);seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int p,boolean u){if(u&&mp!=null)mp.seekTo(p);}});
  LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);Button open=btn("OPEN");play=btn("PLAY");Button full=btn("FULL VISUAL");row.addView(open,lp());row.addView(play,lp());row.addView(full,lp());panel.addView(row);
  open.setOnClickListener(v->pick());play.setOnClickListener(v->toggle());full.setOnClickListener(v->panel.setVisibility(panel.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));
  FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);pp.setMargins(d(8),0,d(8),d(8));root.addView(panel,pp);
  TextView tag=t("LIVE • 3D AUDIO REACTIVE",11,0xffeeeeff);tag.setGravity(Gravity.CENTER);tag.setBackgroundColor(0x66000000);FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(d(190),d(32),Gravity.TOP|Gravity.CENTER_HORIZONTAL);tp.topMargin=d(16);root.addView(tag,tp);
  setContentView(root);
 }
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("audio/*");startActivityForResult(i,PICK);}
 @Override protected void onActivityResult(int r,int c,Intent x){super.onActivityResult(r,c,x);if(r!=PICK||c!=RESULT_OK||x==null)return;Uri u=x.getData();try{release();mp=new MediaPlayer();mp.setDataSource(this,u);mp.setOnPreparedListener(p->{song.setText("♪ "+name(u));play.setText("PAUSE");attach(p.getAudioSessionId());p.start();});mp.setOnCompletionListener(p->play.setText("PLAY"));play.setText("LOADING");mp.prepareAsync();}catch(Exception e){song.setText("Could not open track");play.setText("PLAY");}}
 void attach(int id){try{if(av!=null)av.release();av=new Visualizer(id);av.setCaptureSize(Visualizer.getCaptureSizeRange()[1]);av.setDataCaptureListener(new Visualizer.OnDataCaptureListener(){public void onWaveFormDataCapture(Visualizer v,byte[] w,int rate){viz.r.setWave(w);}public void onFftDataCapture(Visualizer v,byte[] f,int rate){viz.r.setFft(f);}},Visualizer.getMaxCaptureRate()/2,true,true);av.setEnabled(true);}catch(Exception e){}}
 void toggle(){if(mp==null){pick();return;}if(mp.isPlaying()){mp.pause();play.setText("PLAY");}else{mp.start();play.setText("PAUSE");}}
 void release(){if(av!=null){try{av.release();}catch(Exception e){}av=null;}if(mp!=null){try{mp.release();}catch(Exception e){}mp=null;}}
 @Override protected void onDestroy(){h.removeCallbacks(clock);release();super.onDestroy();}
 TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);return b;}LinearLayout.LayoutParams lp(){return new LinearLayout.LayoutParams(0,d(48),1);}int d(int n){return Math.round(n*getResources().getDisplayMetrics().density);}String fmt(int m){return String.format(Locale.US,"%d:%02d",Math.max(0,m)/60000,(Math.max(0,m)/1000)%60);}String name(Uri u){String s=u.getLastPathSegment();if(s==null)return "Track";int q=s.lastIndexOf('/');return q<0?s:s.substring(q+1);}

 static class VizView extends android.opengl.GLSurfaceView{final R r;VizView(Context c){super(c);setEGLContextClientVersion(2);r=new R();setRenderer(r);setRenderMode(RENDERMODE_CONTINUOUSLY);}}
 static class R implements android.opengl.GLSurfaceView.Renderer{
  float bass,mid,high,energy;long start;int prog,pos,col;
  void setFft(byte[] b){if(b==null)return;float[] a=new float[64];for(int i=0;i<64;i++){int k=Math.min(b.length-2,2+i*2);float re=b[k],im=b[k+1];a[i]=Math.min(1,(float)Math.hypot(re,im)/110);}bass=sm(a,0,8);mid=sm(a,8,28);high=sm(a,28,64);energy=Math.min(1,bass*1.8f+mid*.7f+high*.35f);}
  void setWave(byte[] w){if(w==null||w.length==0)return;float s=0;for(byte x:w)s+=Math.abs(x);energy=Math.max(energy,Math.min(1,s/w.length/60));}
  float sm(float[]a,int x,int y){float s=0;for(int i=x;i<y;i++)s+=a[i];return s/(y-x);}
  public void onSurfaceCreated(javax.microedition.khronos.egl.EGLConfig c){start=System.nanoTime();String vs="attribute vec3 p;attribute vec3 c;varying vec3 v;void main(){float z=max(.12,1.-p.z*.55);gl_Position=vec4(p.x/z,p.y/z,0.,1.);gl_PointSize=2.5+5.*(1.-p.z);v=c;}";String fs="precision mediump float;varying vec3 v;void main(){float d=length(gl_PointCoord-.5);float a=1.-smoothstep(.05,.5,d);gl_FragColor=vec4(v,a);}";int v=sh(35633,vs),f=sh(35632,fs);prog=android.opengl.GLES20.glCreateProgram();android.opengl.GLES20.glAttachShader(prog,v);android.opengl.GLES20.glAttachShader(prog,f);android.opengl.GLES20.glLinkProgram(prog);pos=android.opengl.GLES20.glGetAttribLocation(prog,"p");col=android.opengl.GLES20.glGetAttribLocation(prog,"c");}
  int sh(int type,String s){int x=android.opengl.GLES20.glCreateShader(type);android.opengl.GLES20.glShaderSource(x,s);android.opengl.GLES20.glCompileShader(x);return x;}
  public void onSurfaceChanged(javax.microedition.khronos.opengles.GL10 g,int w,int h){android.opengl.GLES20.glViewport(0,0,w,h);}
  public void onDrawFrame(javax.microedition.khronos.opengles.GL10 g){float t=(System.nanoTime()-start)/1e9f;float beat=Math.min(1,bass*2.7f);android.opengl.GLES20.glClearColor(.005f+.025f*high,.002f+.018f*mid,.018f+.05f*bass,1);android.opengl.GLES20.glClear(android.opengl.GLES20.GL_COLOR_BUFFER_BIT);android.opengl.GLES20.glUseProgram(prog);android.opengl.GLES20.glEnable(android.opengl.GLES20.GL_BLEND);android.opengl.GLES20.glBlendFunc(android.opengl.GLES20.GL_SRC_ALPHA,android.opengl.GLES20.GL_ONE);scene(t,beat);}
  void scene(float t,float beat){
   int n=180;float[] a=new float[n*6];for(int i=0;i<n;i++){float z=(i%30)/30f;float ang=i*2.399f+t*(.18f+high*.55f);float rad=.16f+z*.82f+beat*.08f;a[i*6]=(float)Math.cos(ang)*rad;a[i*6+1]=(float)Math.sin(ang)*rad*.68f;a[i*6+2]=z;a[i*6+3]=.2f+.7f*(1-z);a[i*6+4]=.25f+.5f*high;a[i*6+5]=1f;}draw(a,android.opengl.GLES20.GL_POINTS,n);
   for(int k=0;k<6;k++){n=72;a=new float[n*6];float rad=.18f+k*.15f+beat*.04f;for(int i=0;i<n;i++){float ang=i*(float)Math.PI*2/n+t*(.2f+k*.035f);a[i*6]=(float)Math.cos(ang)*rad;a[i*6+1]=(float)Math.sin(ang)*rad*.7f;a[i*6+2]=.15f+k*.1f;a[i*6+3]=.35f+.1f*k;a[i*6+4]=.2f+.1f*high;a[i*6+5]=1f;}draw(a,android.opengl.GLES20.GL_LINE_LOOP,n);}
   n=32;a=new float[n*12];for(int i=0;i<n;i++){float x=-.92f+i*.059f;float h=.05f+Math.min(1,(i<16?bass:mid)*1.9f)*(0.2f+.55f*((float)Math.sin(t*2+i*.7f)+1)/2);int q=i*12;a[q]=x;a[q+1]=-.86f;a[q+2]=0;a[q+3]=x;a[q+4]=-.86f+h;a[q+5]=0;a[q+6]=.15f+.5f*high;a[q+7]=.15f+.6f*bass;a[q+8]=1;a[q+9]=a[q+6];a[q+10]=a[q+7];a[q+11]=1;}draw(a,android.opengl.GLES20.GL_LINES,n*2);
   n=96;a=new float[n*6];float rr=.16f+.07f*beat;for(int i=0;i<n;i++){float ang=i*(float)Math.PI*2/n;float wob=1+.15f*(float)Math.sin(i*3+t*3);a[i*6]=(float)Math.cos(ang)*rr*wob;a[i*6+1]=(float)Math.sin(ang)*rr*wob;a[i*6+2]=.58f;a[i*6+3]=.9f;a[i*6+4]=.2f+.7f*high;a[i*6+5]=1;}draw(a,android.opengl.GLES20.GL_LINE_LOOP,n);
  }
  void draw(float[] x,int mode,int count){java.nio.FloatBuffer b=java.nio.ByteBuffer.allocateDirect(x.length*4).order(java.nio.ByteOrder.nativeOrder()).asFloatBuffer();b.put(x).position(0);android.opengl.GLES20.glEnableVertexAttribArray(pos);android.opengl.GLES20.glVertexAttribPointer(pos,3,android.opengl.GLES20.GL_FLOAT,false,24,b);b.position(3);android.opengl.GLES20.glEnableVertexAttribArray(col);android.opengl.GLES20.glVertexAttribPointer(col,3,android.opengl.GLES20.GL_FLOAT,false,24,b);android.opengl.GLES20.glDrawArrays(mode,0,count);android.opengl.GLES20.glDisableVertexAttribArray(pos);android.opengl.GLES20.glDisableVertexAttribArray(col);}
 }
}